=== prowim/prowim/ebcot-rap-framework/src/org/prowim/rap/framework/i18n/resources.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT resources ((ratioGroups?),(group)*) >

<!ELEMENT group ((group | action | image | attribute | label | enumAttribute | enumAttributeWithNull | enumFunction | composedText | text | menu)*) >
<!ATTLIST group id CDATA #REQUIRED >


<!ELEMENT ratioGroups (ratioGroup)+>
<!ATTLIST ratioGroups id CDATA #REQUIRED >

<!ELEMENT ratioGroup (perspective)+>
<!ATTLIST ratioGroup value CDATA #REQUIRED >
<!ATTLIST ratioGroup name CDATA #REQUIRED >
<!ATTLIST ratioGroup ratios CDATA #REQUIRED >
<!ATTLIST ratioGroup templates CDATA #REQUIRED >

<!ELEMENT perspective EMPTY>
<!ATTLIST perspective value CDATA #REQUIRED >
<!ATTLIST perspective name CDATA #REQUIRED >


<!ELEMENT action EMPTY >
<!ATTLIST action id CDATA #REQUIRED >
<!ATTLIST action label CDATA #IMPLIED>
<!ATTLIST action mnemonic CDATA #IMPLIED >
<!ATTLIST action accelerator CDATA #IMPLIED>
<!ATTLIST action src CDATA #IMPLIED>
<!ATTLIST action tooltip CDATA #IMPLIED>

<!ELEMENT label EMPTY >
<!ATTLIST label id CDATA #REQUIRED >
<!ATTLIST label text CDATA #IMPLIED>
<!ATTLIST label src CDATA #IMPLIED>
<!ATTLIST label tooltip CDATA #IMPLIED>

<!ELEMENT menu EMPTY >
<!ATTLIST menu id CDATA #REQUIRED >
<!ATTLIST menu label CDATA #IMPLIED>
<!ATTLIST menu mnemonic CDATA #IMPLIED>
<!ATTLIST menu src CDATA #IMPLIED>

<!ELEMENT image EMPTY >
<!ATTLIST image id CDATA #REQUIRED >
<!ATTLIST image src CDATA #REQUIRED >

<!ELEMENT text (#PCDATA)>
<!ATTLIST text id CDATA #REQUIRED>
<!ELEMENT composedText (#PCDATA|argument)*>
<!ATTLIST composedText id CDATA #REQUIRED >

<!ELEMENT argument EMPTY>
<!ATTLIST argument index CDATA #REQUIRED>
<!ATTLIST argument type (choice|date|number|time) #IMPLIED>
<!ATTLIST argument style CDATA #IMPLIED>


<!ELEMENT attribute EMPTY>
<!ATTLIST attribute id CDATA #REQUIRED >
<!ATTLIST attribute label CDATA #REQUIRED >
<!ATTLIST attribute tooltip CDATA #IMPLIED >

<!ELEMENT enumAttribute ( enum+ ) >
<!ATTLIST enumAttribute id CDATA #REQUIRED >
<!ATTLIST enumAttribute label CDATA #REQUIRED >
<!ATTLIST enumAttribute tooltip CDATA #IMPLIED >

<!ELEMENT enumAttributeWithNull ( enum+ ) >
<!ATTLIST enumAttributeWithNull id CDATA #REQUIRED >
<!ATTLIST enumAttributeWithNull label CDATA #REQUIRED >
<!ATTLIST enumAttributeWithNull tooltip CDATA #IMPLIED >
<!ATTLIST enumAttributeWithNull nullLabel CDATA #IMPLIED >


<!ELEMENT enum EMPTY >
<!ATTLIST enum label CDATA #REQUIRED >
<!ATTLIST enum value CDATA #REQUIRED >

<!ELEMENT enumFunction ( func+ ) >
<!ATTLIST enumFunction id CDATA #REQUIRED >
<!ATTLIST enumFunction label CDATA #REQUIRED >
<!ATTLIST enumFunction tooltip CDATA #IMPLIED >

<!ELEMENT func EMPTY >
<!ATTLIST func function CDATA #REQUIRED >
<!ATTLIST func description CDATA #REQUIRED >

=== prowim/prowim/ebcot-rap-framework/src/org/prowim/rap/framework/i18n/resources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "resources.dtd" [
    <!ENTITY contentProperty "Dokumenteigenschaften">
    <!ENTITY contentProperties "Dokumenteneigenschaften"> 
    <!ENTITY document "Dokument">
    <!ENTITY documents "Dokumente"> 
    <!ENTITY version "Version">
    <!ENTITY versions "Versionen"> 
    <!ENTITY versionHistory "Versionshistorie">
    <!ENTITY versionHistories "Historie der Versionen"> 
    ]>
    <!-- TODO siehe Task "3685: Internationalisierung der Entitäten"--> 
    <!--
        This is the XML document defined by resource.dtd used by ProWim Maziar 
        Khodaei, Ebcot GmbH, 13.05.2009 Example for accelerator: * "INSERT" =>
        getKeyStroke(KeyEvent.VK_INSERT, 0); * "control DELETE" =>
        getKeyStroke(KeyEvent.VK_DELETE, InputEvent.CTRL_MASK); * "alt shift
        X" => getKeyStroke(KeyEvent.VK_X, InputEvent.ALT_MASK |
        InputEvent.SHIFT_MASK); * "alt shift released X" =>
        getKeyStroke(KeyEvent.VK_X, InputEvent.ALT_MASK |
        InputEvent.SHIFT_MASK, true); * "typed a" => getKeyStroke('a');

        Example grouping: <group id="TEST"> <attribute id="NAME" label="Name"
        tooltip="Name of shirt."/> <enumAttribute id="SIZE" label="Size"
        tooltip="Shirt size."> <enum label="S" value="1"/> <enum label="M"
        value="2"/> <enum label="L" value="3"/> </enumAttribute>
        <enumAttributeWithNull id="COLOR" label="Color" tooltip="Color of
        shirt." nullLabel="Choose color:"> <enum label="Red." value="1"/>
        <enum label="Green." value="2"/> <enum label="Blue." value="3"/>
        </enumAttributeWithNull> <composedText id="ORDER"> You ordered
        <argument index="0" type="number" style="integer"/> shirt<argument
        index="0" type="choice" style="0#s|1#|3#s"/>. </composedText> <text
        id="COPYRIGHT"> God of the greedy. </text> </group>
    -->
<resources>
    <group id="FRAMES">
        <group id="GLOBAL">
           <group id="TEXTS">
           </group>
           <group id="IMAGES">
           </group>
           <group id="ACTIONS">
                <action id="ITEM_ADD" label="Element hinzufügen"  src="img/toolbar/add.png" tooltip="Einen Element zu der Liste hinzufügen."/>
                <action id="ITEM_DELETE" label="Element löschen"  src="img/toolbar/delete.png" tooltip="Ausgewählter Element aus der Liste löschen."/>
           </group>
        </group>
        <group id="DIALOG">
            <group id="ACTIONS">
            </group>
            <group id="IMAGES">
            </group>
            <group id="TEXTS">
            </group>
        </group>
        <group id="HEADER">
            <group id="ACTIONS">
            </group>
            <group id="TEXTS">
            </group>
            <group id="IMAGES">
            </group>
        </group>
        <group id="NAVIGATION">
            <group id="ACTIONS">
            </group>
           <group id="IMAGES">
            </group>
        </group>
        <group id="TOOLBAR">
            <group id="IMAGES">
            </group>
            <group id="ACTIONS">
            </group>
        </group>   
        <group id="PROCESS">
            <group id="ACTIONS">
            </group>
            <group id="TEXTS">
            </group>
            <group id="IMAGES">
            </group>            
        </group>  
        <group id="ACTIVITY">
            <group id="ACTIONS">
            </group>
            <group id="TEXTS">
            </group>
            <group id="IMAGES">
            </group>            
        </group>    
        <group id="TREE">
            <group id="ACTIONS">
            </group>
            <group id="IMAGES">
            </group>   
            <group id="TEXTS">
            </group>
        </group>    
        <group id="KNOWLEDGE">
            <group id="ACTIONS">
            </group>
            <group id="TEXTS">
            </group>
            <group id="IMAGES">
            </group>            
        </group>    
        <group id="TABLE">
            <group id="ACTIONS">
            </group>
        </group>
    </group>

        <!-- TODO siehe Task "3685: Internationalisierung der Entitäten" 
    <group id="VALUE_OBJECTS">
        <text id="UNIQUE_KEY">Index</text>
        <group id="DOCUMENT">
            <text id="VO_NAME_SINGULAR">&document;</text>
            <text id="VO_NAME_PLURAL">&documents;</text>
            <attribute id="NAME" label="Name"/>
            <attribute id="TYPE" label="Typ"/>
            <attribute id="SIZE" label="Dateigröße"/>
            <attribute id="FORMAT" label="Format"/>
            <attribute id="CONTENT" label="Datei"/>
        </group>
    </group>-->
    
</resources>
